/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/LastBlock": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.LastBlock.id"];
          blockNumber?: parameters["rowFilter.LastBlock.blockNumber"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["LastBlock"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** LastBlock */
          LastBlock?: definitions["LastBlock"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.LastBlock.id"];
          blockNumber?: parameters["rowFilter.LastBlock.blockNumber"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.LastBlock.id"];
          blockNumber?: parameters["rowFilter.LastBlock.blockNumber"];
        };
        body: {
          /** LastBlock */
          LastBlock?: definitions["LastBlock"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/Event": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Event.id"];
          blockNumber?: parameters["rowFilter.Event.blockNumber"];
          txHash?: parameters["rowFilter.Event.txHash"];
          txIndex?: parameters["rowFilter.Event.txIndex"];
          logIndex?: parameters["rowFilter.Event.logIndex"];
          removed?: parameters["rowFilter.Event.removed"];
          timestamp?: parameters["rowFilter.Event.timestamp"];
          type?: parameters["rowFilter.Event.type"];
          data?: parameters["rowFilter.Event.data"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Event"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Event */
          Event?: definitions["Event"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Event.id"];
          blockNumber?: parameters["rowFilter.Event.blockNumber"];
          txHash?: parameters["rowFilter.Event.txHash"];
          txIndex?: parameters["rowFilter.Event.txIndex"];
          logIndex?: parameters["rowFilter.Event.logIndex"];
          removed?: parameters["rowFilter.Event.removed"];
          timestamp?: parameters["rowFilter.Event.timestamp"];
          type?: parameters["rowFilter.Event.type"];
          data?: parameters["rowFilter.Event.data"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Event.id"];
          blockNumber?: parameters["rowFilter.Event.blockNumber"];
          txHash?: parameters["rowFilter.Event.txHash"];
          txIndex?: parameters["rowFilter.Event.txIndex"];
          logIndex?: parameters["rowFilter.Event.logIndex"];
          removed?: parameters["rowFilter.Event.removed"];
          timestamp?: parameters["rowFilter.Event.timestamp"];
          type?: parameters["rowFilter.Event.type"];
          data?: parameters["rowFilter.Event.data"];
        };
        body: {
          /** Event */
          Event?: definitions["Event"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  LastBlock: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: integer */
    blockNumber?: number;
  };
  Event: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: bigint */
    blockNumber?: number;
    /** Format: character varying */
    txHash?: string;
    /** Format: integer */
    txIndex?: number;
    /** Format: integer */
    logIndex?: number;
    /** Format: boolean */
    removed?: boolean;
    /** Format: bigint */
    timestamp?: number;
    /** Format: text */
    type?: string;
    /** Format: jsonb */
    data?: unknown;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferPost:
    | "return=representation"
    | "return=minimal"
    | "return=none"
    | "resolution=ignore-duplicates"
    | "resolution=merge-duplicates";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description LastBlock */
  "body.LastBlock": definitions["LastBlock"];
  /** Format: integer */
  "rowFilter.LastBlock.id": string;
  /** Format: integer */
  "rowFilter.LastBlock.blockNumber": string;
  /** @description Event */
  "body.Event": definitions["Event"];
  /** Format: integer */
  "rowFilter.Event.id": string;
  /** Format: bigint */
  "rowFilter.Event.blockNumber": string;
  /** Format: character varying */
  "rowFilter.Event.txHash": string;
  /** Format: integer */
  "rowFilter.Event.txIndex": string;
  /** Format: integer */
  "rowFilter.Event.logIndex": string;
  /** Format: boolean */
  "rowFilter.Event.removed": string;
  /** Format: bigint */
  "rowFilter.Event.timestamp": string;
  /** Format: text */
  "rowFilter.Event.type": string;
  /** Format: jsonb */
  "rowFilter.Event.data": string;
}

export interface operations {}

export interface external {}
